# Generated by Django 5.2.10 on 2026-03-13 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkloadNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do documento (ex: "Resolução CONSUP/IFPE nº 8/2020")', max_length=200, verbose_name='Nome')),
                ('resolution_number', models.CharField(help_text='Número identificador (ex: "8/2020")', max_length=50, verbose_name='Número da Resolução')),
                ('effective_date', models.DateField(verbose_name='Data de Vigência')),
                ('is_active', models.BooleanField(default=False, help_text='Somente uma normatização deve estar ativa por vez', verbose_name='Ativa')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Normatização Docente',
                'verbose_name_plural': 'Normatizações Docentes',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'ordering': ['name'], 'verbose_name': 'Professor', 'verbose_name_plural': 'Professores'},
        ),
        migrations.AddField(
            model_name='professor',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('DE', 'DE — Dedicação Exclusiva'), ('40h', '40h'), ('20h', '20h')], help_text='Formato do vínculo contratual', max_length=5, verbose_name='Regime de Trabalho'),
        ),
        migrations.AddField(
            model_name='professor',
            name='work_group',
            field=models.CharField(blank=True, choices=[('I', 'Grupo I'), ('II', 'Grupo II'), ('III', 'Grupo III'), ('IV', 'Grupo IV'), ('V', 'Grupo V'), ('VI', 'Grupo VI')], help_text='Grupo docente conforme normatização do IFPE', max_length=5, verbose_name='Grupo de Trabalho'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='name',
            field=models.CharField(help_text='Nome completo do professor', max_length=200, verbose_name='Nome'),
        ),
        migrations.CreateModel(
            name='WorkloadNormEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_group', models.CharField(choices=[('I', 'Grupo I'), ('II', 'Grupo II'), ('III', 'Grupo III'), ('IV', 'Grupo IV'), ('V', 'Grupo V'), ('VI', 'Grupo VI')], max_length=5, verbose_name='Grupo')),
                ('contract_type', models.CharField(choices=[('40h_DE', '40h / DE'), ('20h', '20h')], max_length=10, verbose_name='Regime')),
                ('class_duration', models.IntegerField(choices=[(45, '45 min'), (50, '50 min'), (60, '60 min')], verbose_name='Tempo de Aula (min)')),
                ('min_classes', models.PositiveIntegerField(blank=True, help_text='Nulo = N/A para esta combinação', null=True, verbose_name='Mín. Aulas/Semana')),
                ('max_classes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Máx. Aulas/Semana')),
                ('norm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='professors.workloadnorm', verbose_name='Normatização')),
            ],
            options={
                'verbose_name': 'Entrada de Normatização',
                'verbose_name_plural': 'Entradas de Normatização',
                'ordering': ['work_group', 'contract_type', 'class_duration'],
                'unique_together': {('norm', 'work_group', 'contract_type', 'class_duration')},
            },
        ),
    ]
