# Generated by Django 5.2.10 on 2026-03-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0003_populate_resolucao_8_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='is_on_leave',
            field=models.BooleanField(default=False, help_text='Professor afastado não entra no cômputo da soma total de esforço', verbose_name='Afastado'),
        ),
    ]
