# Generated by Django 5.2.10 on 2026-03-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0004_professor_is_on_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Desmarque para professores que saíram do curso. O histórico de aulas é preservado.', verbose_name='Disponível para distribuição'),
        ),
    ]
