# Generated by Django 6.0.1 on 2026-01-12 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Course Name')),
                ('calendar_type', models.CharField(choices=[('semestral', 'Semestral'), ('yearly', 'Yearly')], default='semestral', max_length=20, verbose_name='Calendar Type')),
                ('description', models.TextField(blank=True, help_text='Description of the course program to be used for effort calculation', verbose_name='Course Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Discipline Name')),
                ('period', models.CharField(help_text='Semester or year when the discipline is offered', max_length=20, verbose_name='Period')),
                ('main_area', models.CharField(help_text='Main knowledge area to be matched with professors', max_length=200, verbose_name='Main Area')),
                ('description', models.TextField(blank=True, help_text='Description of the discipline to be used for effort calculation', verbose_name='Discipline Description')),
                ('workload_hours', models.PositiveIntegerField(default=60, help_text='Total workload in hours', verbose_name='Workload (hours)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='courses.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Discipline',
                'verbose_name_plural': 'Disciplines',
                'ordering': ['course', 'period', 'name'],
            },
        ),
    ]
