# Generated by Django 5.2.10 on 2026-01-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='workload_hours',
        ),
        migrations.AddField(
            model_name='course',
            name='grade_year',
            field=models.CharField(default='2019.2', help_text='Academic year/period of the course curriculum (e.g., 2019.2)', max_length=20, verbose_name='Grade Year'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='ch_aula',
            field=models.PositiveIntegerField(default=0, help_text='Classroom hours (carga horária aula)', verbose_name='CH Aula'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='ch_relogio',
            field=models.PositiveIntegerField(default=0, help_text='Clock hours (carga horária relógio)', verbose_name='CH Relógio'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='co_requisito',
            field=models.CharField(blank=True, help_text='Co-requisite discipline(s)', max_length=500, verbose_name='Co-requisite'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='credits',
            field=models.PositiveIntegerField(default=0, help_text='Number of credits', verbose_name='Credits'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='pre_requisito',
            field=models.CharField(blank=True, help_text='Prerequisite discipline(s)', max_length=500, verbose_name='Prerequisite'),
        ),
    ]
