# Generated by Django 5.2.10 on 2026-01-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_discipline_workload_hours_course_grade_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='is_elective',
            field=models.BooleanField(default=False, help_text='Indicates if the discipline is elective', verbose_name='Optativa'),
        ),
    ]
