# Generated by Django 5.2.10 on 2026-01-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_discipline_is_elective'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='available_periods',
            field=models.CharField(blank=True, help_text="Periods when elective can be taken (e.g., '5,6' for periods 5 and 6)", max_length=50, verbose_name='Available Periods'),
        ),
    ]
