# Generated by Django 5.2.10 on 2026-03-13 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_discipline_available_periods'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseElectiveSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text="Período em que as optativas são ofertadas (ex: '5')", max_length=20, verbose_name='Período')),
                ('count', models.PositiveIntegerField(default=1, help_text='Número de disciplinas optativas ofertadas neste período', verbose_name='Qtd. de Optativas')),
                ('credits', models.PositiveIntegerField(default=0, help_text='Créditos de cada disciplina optativa (conforme PPC)', verbose_name='Créditos por Optativa')),
                ('ch_relogio', models.PositiveIntegerField(default=0, help_text='Carga horária relógio de cada optativa (conforme PPC)', verbose_name='CH por Optativa (h)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elective_slots', to='courses.course', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Configuração de Optativas',
                'verbose_name_plural': 'Configurações de Optativas',
                'ordering': ['period'],
                'unique_together': {('course', 'period')},
            },
        ),
    ]
