# Generated by Django 5.2.10 on 2026-03-13 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_courseelectiveslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='short_name',
            field=models.CharField(blank=True, help_text='Sigla ou nome curto para exibição (ex: "ADS", "TII")', max_length=20, verbose_name='Abreviação'),
        ),
    ]
