# Generated by Django 5.2.10 on 2026-03-22 16:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0006_course_short_name'),
        ('professors', '0004_professor_is_on_leave'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('semester', models.CharField(help_text='Ex: "2025.1", "2025.2"', max_length=10, validators=[django.core.validators.RegexValidator(message='Formato inválido. Use AAAA.1 ou AAAA.2 (ex: 2025.1)', regex='^\\d{4}\\.[12]$')], verbose_name='Semestre')),
                ('class_duration', models.IntegerField(choices=[(45, '45 min'), (50, '50 min'), (60, '60 min')], default=45, help_text='Usado para calcular os limites de carga horária conforme norma vigente', verbose_name='Tempo de Aula (min)')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grade Semestral',
                'verbose_name_plural': 'Grades Semestrais',
                'ordering': ['-semester', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_label', models.CharField(blank=True, help_text='Ex: "Turma A", "T01"', max_length=50, verbose_name='Rótulo da Turma')),
                ('weekly_classes', models.PositiveIntegerField(default=1, help_text='Número de aulas por semana para esta turma', verbose_name='Aulas Semanais')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_classes', to='courses.discipline', verbose_name='Disciplina')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_classes', to='scheduling.semesterschedule', verbose_name='Grade')),
            ],
            options={
                'verbose_name': 'Turma Ofertada',
                'verbose_name_plural': 'Turmas Ofertadas',
                'ordering': ['discipline__course__name', 'discipline__period', 'discipline__name', 'class_label'],
            },
        ),
        migrations.CreateModel(
            name='ClassAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='professors.professor', verbose_name='Professor')),
                ('scheduled_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='scheduling.scheduledclass', verbose_name='Turma Ofertada')),
            ],
            options={
                'verbose_name': 'Atribuição de Professor',
                'verbose_name_plural': 'Atribuições de Professores',
                'ordering': ['professor__name'],
                'unique_together': {('scheduled_class', 'professor')},
            },
        ),
    ]
