# Generated by Django 5.2.10 on 2026-03-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledclass',
            options={'ordering': ['discipline__course__name', 'discipline__period', 'discipline__name', 'turno', 'class_label'], 'verbose_name': 'Turma Ofertada', 'verbose_name_plural': 'Turmas Ofertadas'},
        ),
        migrations.AddField(
            model_name='scheduledclass',
            name='turno',
            field=models.CharField(blank=True, choices=[('M', 'Manhã'), ('T', 'Tarde'), ('N', 'Noite')], max_length=1, verbose_name='Turno'),
        ),
    ]
