# Generated by Django 5.2.10 on 2026-01-17 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_remove_discipline_workload_hours_course_grade_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name to identify this semester plan (e.g., "2024.1 Planning")', max_length=200, verbose_name='Plan Name')),
                ('description', models.TextField(blank=True, help_text='Additional notes about this plan', verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_plans', to='courses.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Semester Plan',
                'verbose_name_plural': 'Semester Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes_count', models.PositiveIntegerField(default=1, help_text='Number of classes for this discipline (usually 1, but can be more for extra classes)', verbose_name='Number of Classes')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this discipline in the plan', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_items', to='courses.discipline', verbose_name='Discipline')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_items', to='planning.semesterplan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Plan Discipline',
                'verbose_name_plural': 'Plan Disciplines',
                'ordering': ['discipline__period', 'discipline__name'],
                'unique_together': {('plan', 'discipline')},
            },
        ),
    ]
