# Generated by Django 5.2.10 on 2026-01-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semesterplan',
            options={'ordering': ['-semester', '-created_at'], 'verbose_name': 'Semester Plan', 'verbose_name_plural': 'Semester Plans'},
        ),
        migrations.AddField(
            model_name='semesterplan',
            name='semester',
            field=models.CharField(default='', help_text='Semester identifier (e.g., "2024.1", "2024.2")', max_length=20, verbose_name='Semester'),
            preserve_default=False,
        ),
    ]
