# Generated by Django 5.2.10 on 2026-01-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_alter_semesterplan_options_semesterplan_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandiscipline',
            name='assigned_period',
            field=models.CharField(blank=True, help_text='Period where this elective discipline will be offered', max_length=20, verbose_name='Assigned Period'),
        ),
    ]
