# Generated by Django 5.2.10 on 2026-03-12 23:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_discipline_available_periods'),
        ('planning', '0003_plandiscipline_assigned_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_semester', models.CharField(help_text='Semestre em que a turma inicia (ex: "2026.1")', max_length=10, validators=[django.core.validators.RegexValidator(message='Formato inválido. Use AAAA.1 ou AAAA.2 (ex: 2026.1)', regex='^\\d{4}\\.[12]$')], verbose_name='Semestre de Início')),
                ('label', models.CharField(blank=True, help_text='Nome opcional para identificar a turma (ex: "Turma A")', max_length=100, verbose_name='Rótulo')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarque para excluir da projeção sem deletar', verbose_name='Ativa')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_entries', to='courses.course', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Entrada de Turma',
                'verbose_name_plural': 'Entradas de Turma',
                'ordering': ['start_semester', 'course__name'],
            },
        ),
        migrations.CreateModel(
            name='ExtraClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(help_text='Semestre em que a disciplina extra será ofertada (ex: "2026.1")', max_length=10, validators=[django.core.validators.RegexValidator(message='Formato inválido. Use AAAA.1 ou AAAA.2 (ex: 2026.1)', regex='^\\d{4}\\.[12]$')], verbose_name='Semestre')),
                ('extra_count', models.PositiveIntegerField(default=1, verbose_name='Número de Turmas Extras')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_classes', to='courses.course', verbose_name='Curso')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_classes', to='courses.discipline', verbose_name='Disciplina')),
            ],
            options={
                'verbose_name': 'Disciplina Extra',
                'verbose_name_plural': 'Disciplinas Extras',
                'ordering': ['semester', 'discipline__name'],
                'unique_together': {('discipline', 'semester')},
            },
        ),
    ]
